export const UPDATE_COMMENT = 'UPDATE_COMMENT';
export const SET_TOKEN = 'SET_TOKEN';
export const ME_REQUEST = 'ME_REQUEST';
export const ME_REQUEST_ERROR = 'ME_REQUEST_ERROR';
export const ME_REQUEST_SUCCESS = 'ME_REQUEST_SUCCESS';
export const POSTS_REQUEST = 'POSTS_REQUEST';
export const POSTS_REQUEST_ERROR = 'POSTS_REQUEST_ERROR';
export const POSTS_REQUEST_SUCCESS = 'POSTS_REQUEST_SUCCESS';
export const COMMENTS_REQUEST = 'COMMENTS_REQUEST';
export const COMMENTS_REQUEST_ERROR = 'COMMENTS_REQUEST_ERROR';
export const COMMENTS_REQUEST_SUCCESS = 'COMMENTS_REQUEST_SUCCESS';

export const RISING_POSTS_REQUEST = 'RISING_POSTS_REQUEST';
export const RISING_POSTS_REQUEST_AFTER = 'RISING_POSTS_REQUEST_AFTER';
export const RISING_POSTS_REQUEST_COUNT = 'RISING_POSTS_REQUEST_COUNT';
export const RISING_POSTS_REQUEST_ERROR = 'RISING_POSTS_REQUEST_ERROR';
export const RISING_POSTS_REQUEST_SUCCESS = 'RISING_POSTS_REQUEST_SUCCESS';